variables:
  buildConfiguration: Release

trigger:
- master

stages:
- stage: Build
  pool:
   vmImage: 'ubuntu-latest'
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
      displayName: Restore
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--no-restore --configuration $(buildConfiguration)'
      displayName: Build

  - job: UnitTests
    dependsOn: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*UnitTests.csproj'
        arguments: '--no-restore --no-build --configuration $(buildConfiguration)'
      displayName: Unit tests
  
  - job: IntegrationTests
    dependsOn: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*IntegrationTests.csproj'
        arguments: '--no-restore --no-build --configuration $(buildConfiguration)'
      displayName: Integration tests

  - job: Publish
    dependsOn:
    - UnitTests
    - IntegrationTests
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '**/CQRSTrading.WEB.csproj'
          arguments: '--no-restore --no-build --configuration $(buildConfiguration)'
        displayName: Publish

- stage: Release
  dependsOn: Build
  pool:
   vmImage: 'ubuntu-latest'
  jobs:
  - job: Release
    steps:      
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Visual Studio Professional Subscription(648aa60f-e4a7-4f47-b926-e602e78bae5a)'
          appType: 'webApp'
          WebAppName: 'cqrstrading'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        displayName: Deploy